
DROP TABLE IF EXISTS cinema;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS genre;
DROP TABLE IF EXISTS movie;
DROP TABLE IF EXISTS ticket;



CREATE TABLE cinema(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    address VARCHAR(250) NOT NULL
);

CREATE TABLE customer (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstname VARCHAR(25) NOT NULL,
    lastname VARCHAR(25) NOT NULL,
    gender VARCHAR(10) NOT NULL,
    age INT DEFAULT 0,
    phone VARCHAR(10),
    email VARCHAR(25) UNIQUE
);

CREATE TABLE genre(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(25) NOT NULL

);

CREATE TABLE movie(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(75) NOT NULL,
    genre_id INT NOT NULL,
    price INT NOT NULL,
    FOREIGN KEY (genre_id) REFERENCES genre(id),

);

CREATE TABLE ticket(
    id id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INT NOT NULL,
    moviename VARCHAR NOT NULL,
    price DOUBLE NOT NULL,
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (moviename) REFERENCES movie(name)
);
-------------------------------------------
--------------  TEST SAMPLES --------------
-------------------------------------------

INSERT INTO customer(firstname,lastname,gender,age,phone,email)
VALUES ('Burkay','Ozturk','male','26','5554443322','burkay@gmail.com'),
        ('Onur','Cicek','male','28','5554443323','onur@gmail.com'),
        ('Emre','Pep','male','28','5554443324','pep@gmail.com'),
        ('Furkan','Malkoc','male','26','5554443325','fdes@gmail.com'),
        ('Osman','Kara','male','25','5554443326','muhtesemosman@gmail.com'),
        ('Ayse','Yilmaz','female','24','5554443327','ayse@gmail.com'),
        ('Deniz','Kaya','female','25','5554443328','deniz@gmail.com'),
        ('Irem','Demir','female','29','5554443329','demir@gmail.com');

 INSERT INTO genre(name)
 VALUES ('Sci-fi'),
        ('Fantasy'),
        ('Action'),
        ('Comedy'),
        ('Drama'),
        ('Romance');

    INSERT INTO movie (name, genre_id,price)
    VALUES ( 'Spider-Man ','2','30'),
            ( 'Limitless','1','35'),
            ('John Wick', '3','25');
